export const gridSpacing = 3;
export const drawerWidth = 265;
export const librarydrawerWidth = 250;
export const appDrawerWidth = 320;
export const sideBarLogoHeight = 18;
export const sideBarLogoBoxHeight = 22;
export const sideBarHeight = 78;
export const sideBarLogoHeightUpXl = 13;
export const sideBarLogoBoxHeightUpXl = 15;
export const sideBarHeightUpXl = 85;

export const appHeaderMargin = 9;
export const appHeaderHeight = 65;
export const smallHeaderHeight = 70;
export const smallHeaderHeightTablet = 140;
export const smallHeaderHeightMobile = 160;
export const largeHeaderHeight = 160;
export const largeHeaderHeightTablet = 220;
export const largeHeaderHeightMobile = 320;
export const subHeaderHeight = 60;
export const mainLayoutOuterSpacing = 9;
export const mainLayoutInnerSpacing = 2;
export const TableInnerSpacing = 2.5;
export const largeHeaderHeightMdscreen = 180;
export const processedLogBoxHeight = 200;
export const smallHeaderHeightTabletWithoutSerach = 70;
export const dashboradBlankChartHeight = 231;
export const listHeightSmallHeader = `calc(100vh - (${appHeaderHeight}px + ${smallHeaderHeight}px + ${mainLayoutOuterSpacing}px ))`;
export const listHeightSmallHeaderWithFilters = `calc(100vh - (${appHeaderHeight}px + ${smallHeaderHeight}px + ${
    mainLayoutOuterSpacing + 94
}px ))`;
export const listHeightMediumHeader = `calc(100vh - (${appHeaderHeight}px + ${smallHeaderHeight}px + ${mainLayoutOuterSpacing + 8}px ))`;
export const listHeightLargeHeader = `calc(100vh - (${appHeaderHeight}px + ${largeHeaderHeight}px + ${mainLayoutOuterSpacing}px )) `;
export const listHeightSmallHeaderTablet = `calc(100vh - (${appHeaderHeight}px + ${smallHeaderHeightMobile}px + ${mainLayoutOuterSpacing}px ))`;
export const listHeightLargeHeaderTablet = `calc(100vh - (${appHeaderHeight}px + ${largeHeaderHeightMobile}px + ${mainLayoutOuterSpacing}px ))`;
export const listHeightSmallHeaderMobile = `calc(100vh - (${appHeaderHeight}px + ${smallHeaderHeightMobile}px + ${mainLayoutOuterSpacing}px ))`;
export const listHeightLargeHeaderMobile = `calc(100vh - (${appHeaderHeight}px + ${largeHeaderHeightMobile}px + ${mainLayoutOuterSpacing}px ))`;
export const photoViewerBoxHeight = `calc(100vh -  ${mainLayoutOuterSpacing + 120}px ))`;
export const deliveryTime = `10AM - 12PM / 4PM - 6PM`;
